using System;
using System.Collections.Generic;
using System.Globalization;
using Emotional_Mapping.Domain.Enums;

namespace Emotional_Mapping.Web.Localization;

public class SiteText
{
    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new(StringComparer.OrdinalIgnoreCase)
    {
        ["bg"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Lang.Bg"] = "БГ",
            ["Lang.En"] = "EN",
            ["Lang.Label"] = "Език",
            ["Nav.Home"] = "Начало",
            ["Nav.Map"] = "Карта",
            ["Nav.Generate"] = "Генерирай карта",
            ["Nav.Stats"] = "Статистики",
            ["Nav.MyMaps"] = "Моите карти",
            ["Nav.AddPoint"] = "Добави точка",
            ["Nav.SuggestPlace"] = "Предложи място",
            ["Nav.Contact"] = "Контакт",
            ["Nav.Admin"] = "Админ",
            ["Account.Profile"] = "Профил",
            ["Account.Premium"] = "Premium",
            ["Account.NewMap"] = "Нова карта",
            ["Account.ChangePassword"] = "Промени парола",
            ["Account.Logout"] = "Изход",
            ["Auth.Login"] = "Вход",
            ["Auth.Register"] = "Регистрация",
            ["Auth.LoginTitle"] = "Вход в GEOFEEL",
            ["Auth.LoginSub"] = "Влез в профила си, за да генерираш карти, да пазиш история и да използваш premium функции.",
            ["Auth.RegisterTitle"] = "Регистрация в GEOFEEL",
            ["Auth.RegisterSub"] = "Създай профил и започни да генерираш емоционални карти с AI.",
            ["Auth.Email"] = "Имейл",
            ["Auth.Password"] = "Парола",
            ["Auth.DisplayName"] = "Показвано име",
            ["Auth.ConfirmPassword"] = "Потвърди паролата",
            ["Auth.ForgotPassword"] = "Забравена парола?",
            ["Auth.Google"] = "Продължи с Google",
            ["Auth.Apple"] = "Продължи с Apple",
            ["Auth.NoAccount"] = "Нямаш профил?",
            ["Auth.HasAccount"] = "Вече имаш профил?",
            ["Auth.OrContinue"] = "или продължи с",
            ["Auth.NamePlaceholder"] = "Например: Ivan",
            ["Auth.PasswordHint"] = "Паролата трябва да съдържа:",
            ["Auth.PasswordReq1"] = "минимум 6 символа",
            ["Auth.PasswordReq2"] = "поне 1 главна буква",
            ["Auth.PasswordReq3"] = "поне 1 цифра",
            ["Auth.PasswordReq4"] = "поне 1 специален символ",
            ["Hero.Eyebrow"] = "GEOFEEL • AI emotional mapping",
            ["Hero.TitleLine1"] = "Усети града",
            ["Hero.TitleAccent"] = "емоциите",
            ["Hero.TitleLine3"] = "на хората",
            ["Hero.Desc"] = "GEOFEEL визуализира спокойствие, радост, носталгия, вдъхновение и още емоции върху реална карта. Генерирай персонална карта с AI, запази я, сподели я и открий най-подходящите места според настроението си.",
            ["Hero.Primary"] = "Генерирай карта с AI",
            ["Hero.Secondary"] = "Разгледай картата",
            ["Home.HowItWorks"] = "Как работи?",
            ["Home.Feature1Title"] = "Добавяй емоционални точки",
            ["Home.Feature1Desc"] = "Маркирай място, избери емоция, интензитет и описание.",
            ["Home.Feature2Title"] = "AI анализ",
            ["Home.Feature2Desc"] = "Въведи настроение и системата ще генерира карта и препоръки.",
            ["Home.Feature3Title"] = "Интерактивна карта",
            ["Home.Feature3Desc"] = "Визуализирай места, heatmap и емоционални зони.",
            ["Home.Feature4Title"] = "Cloud база данни",
            ["Home.Feature4Desc"] = "Картите и точките се пазят в облачна база, достъпна отвсякъде.",
            ["Home.Feature5Title"] = "Публични карти",
            ["Home.Feature5Desc"] = "Споделяй карта с линк и показвай резултата на други хора.",
            ["Home.Feature6Title"] = "Обратна връзка",
            ["Home.Feature6Desc"] = "Оценявай дали картата отговаря на настроението ти.",
            ["Home.Bubble.Calm"] = "Спокойствие",
            ["Home.Bubble.Joy"] = "Радост",
            ["Home.Bubble.Inspiration"] = "Вдъхновение",
            ["Home.Bubble.Romantic"] = "Романтика",
            ["Home.Bubble.Nostalgia"] = "Носталгия",
            ["Home.Bubble.Relaxed"] = "Релакс",
            ["Home.Bubble.Excited"] = "Еуфория",
            ["Plans.Title"] = "Планове",
            ["Plans.FreeCta"] = "Безплатен старт",
            ["Plans.PremiumCta"] = "Започни сега",
            ["Plans.Upgrade"] = "Надгради със Stripe",
            ["Plans.FreeLimit"] = "До 3 AI генерации на ден",
            ["Plans.FreeFeature2"] = "Стандартна топлинна карта",
            ["Plans.FreeFeature3"] = "Запазване на карти",
            ["Plans.FreeFeature4"] = "Добавяне на точки",
            ["Plans.PriceNote"] = "на месец",
            ["Plans.PremiumLimit"] = "До 10 AI генерации на ден",
            ["Plans.PremiumFeature2"] = "Premium топлинна карта",
            ["Plans.PremiumFeature3"] = "Оценки по райони",
            ["Plans.PremiumFeature4"] = "Запазени маршрути",
            ["Plans.PremiumFeature5"] = "Публични линкове",
            ["Plans.AlreadyPremium"] = "Вече сте Premium",
            ["Contact.Title"] = "Контакт",
            ["Contact.Sub"] = "Изпрати съобщение, въпрос или идея директно към GEOFEEL.",
            ["Contact.Name"] = "Име",
            ["Contact.Email"] = "Имейл",
            ["Contact.Subject"] = "Тема",
            ["Contact.Message"] = "Съобщение",
            ["Contact.Send"] = "Изпрати съобщение",
            ["Contact.NamePlaceholder"] = "Твоето име",
            ["Contact.SubjectPlaceholder"] = "Например: Въпрос за проекта",
            ["Contact.MessagePlaceholder"] = "Напиши съобщението си...",
            ["Admin.Title"] = "Admin панел",
            ["Admin.Sub"] = "Управление на потребители, емоции и AI статистики",
            ["Admin.LoadError"] = "Грешка при зареждане",
            ["Footer.Privacy"] = "Поверителност"
        },
        ["en"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Lang.Bg"] = "BG",
            ["Lang.En"] = "EN",
            ["Lang.Label"] = "Language",
            ["Nav.Home"] = "Home",
            ["Nav.Map"] = "Map",
            ["Nav.Generate"] = "Generate Map",
            ["Nav.Stats"] = "Statistics",
            ["Nav.MyMaps"] = "My Maps",
            ["Nav.AddPoint"] = "Add Point",
            ["Nav.SuggestPlace"] = "Suggest Place",
            ["Nav.Contact"] = "Contact",
            ["Nav.Admin"] = "Admin",
            ["Account.Profile"] = "Profile",
            ["Account.Premium"] = "Premium",
            ["Account.NewMap"] = "New Map",
            ["Account.ChangePassword"] = "Change Password",
            ["Account.Logout"] = "Logout",
            ["Auth.Login"] = "Sign In",
            ["Auth.Register"] = "Register",
            ["Auth.LoginTitle"] = "Sign in to GEOFEEL",
            ["Auth.LoginSub"] = "Sign in to generate maps, keep your history, and use premium features.",
            ["Auth.RegisterTitle"] = "Create your GEOFEEL account",
            ["Auth.RegisterSub"] = "Create an account and start generating emotional AI maps.",
            ["Auth.Email"] = "Email",
            ["Auth.Password"] = "Password",
            ["Auth.DisplayName"] = "Display name",
            ["Auth.ConfirmPassword"] = "Confirm password",
            ["Auth.ForgotPassword"] = "Forgot password?",
            ["Auth.Google"] = "Continue with Google",
            ["Auth.Apple"] = "Continue with Apple",
            ["Auth.NoAccount"] = "Don't have an account?",
            ["Auth.HasAccount"] = "Already have an account?",
            ["Auth.OrContinue"] = "or continue with",
            ["Auth.NamePlaceholder"] = "For example: Ivan",
            ["Auth.PasswordHint"] = "Your password should include:",
            ["Auth.PasswordReq1"] = "at least 6 characters",
            ["Auth.PasswordReq2"] = "at least 1 uppercase letter",
            ["Auth.PasswordReq3"] = "at least 1 digit",
            ["Auth.PasswordReq4"] = "at least 1 special character",
            ["Hero.Eyebrow"] = "GEOFEEL • AI emotional mapping",
            ["Hero.TitleLine1"] = "Feel the city",
            ["Hero.TitleAccent"] = "through emotions",
            ["Hero.TitleLine3"] = "of its people",
            ["Hero.Desc"] = "GEOFEEL visualizes calm, joy, nostalgia, inspiration and more emotions on a real city map. Generate a personalized AI map, save it, share it, and discover places that match your mood.",
            ["Hero.Primary"] = "Generate with AI",
            ["Hero.Secondary"] = "Explore the Map",
            ["Home.HowItWorks"] = "How it works",
            ["Home.Feature1Title"] = "Add emotional points",
            ["Home.Feature1Desc"] = "Mark a place, choose an emotion, intensity, and description.",
            ["Home.Feature2Title"] = "AI analysis",
            ["Home.Feature2Desc"] = "Describe your mood and the system will generate a map with recommendations.",
            ["Home.Feature3Title"] = "Interactive map",
            ["Home.Feature3Desc"] = "Visualize places, heatmaps, and emotional zones.",
            ["Home.Feature4Title"] = "Cloud database",
            ["Home.Feature4Desc"] = "Maps and points are stored in the cloud and available anywhere.",
            ["Home.Feature5Title"] = "Public maps",
            ["Home.Feature5Desc"] = "Share a map with a link and show the result to other people.",
            ["Home.Feature6Title"] = "Feedback loop",
            ["Home.Feature6Desc"] = "Rate whether the generated map matches your mood.",
            ["Home.Bubble.Calm"] = "Calm",
            ["Home.Bubble.Joy"] = "Joy",
            ["Home.Bubble.Inspiration"] = "Inspiration",
            ["Home.Bubble.Romantic"] = "Romance",
            ["Home.Bubble.Nostalgia"] = "Nostalgia",
            ["Home.Bubble.Relaxed"] = "Relax",
            ["Home.Bubble.Excited"] = "Euphoria",
            ["Plans.Title"] = "Plans",
            ["Plans.FreeCta"] = "Start Free",
            ["Plans.PremiumCta"] = "Get Started",
            ["Plans.Upgrade"] = "Upgrade with Stripe",
            ["Plans.FreeLimit"] = "Up to 3 AI generations per day",
            ["Plans.FreeFeature2"] = "Standard heat map",
            ["Plans.FreeFeature3"] = "Saved maps",
            ["Plans.FreeFeature4"] = "Add emotional points",
            ["Plans.PriceNote"] = "per month",
            ["Plans.PremiumLimit"] = "Up to 10 AI generations per day",
            ["Plans.PremiumFeature2"] = "Premium heat map",
            ["Plans.PremiumFeature3"] = "District scores",
            ["Plans.PremiumFeature4"] = "Saved routes",
            ["Plans.PremiumFeature5"] = "Public links",
            ["Plans.AlreadyPremium"] = "You are already Premium",
            ["Contact.Title"] = "Contact",
            ["Contact.Sub"] = "Send a message, question, or idea directly to GEOFEEL.",
            ["Contact.Name"] = "Name",
            ["Contact.Email"] = "Email",
            ["Contact.Subject"] = "Subject",
            ["Contact.Message"] = "Message",
            ["Contact.Send"] = "Send message",
            ["Contact.NamePlaceholder"] = "Your name",
            ["Contact.SubjectPlaceholder"] = "For example: Question about the project",
            ["Contact.MessagePlaceholder"] = "Write your message...",
            ["Admin.Title"] = "Admin Panel",
            ["Admin.Sub"] = "Manage users, emotions, and AI statistics",
            ["Admin.LoadError"] = "Failed to load",
            ["Footer.Privacy"] = "Privacy"
        }
    };

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        var lang = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;

        if (Strings.TryGetValue(lang, out var current) && current.TryGetValue(key, out var value))
            return value;

        if (Strings["bg"].TryGetValue(key, out var fallback))
            return fallback;

        return key;
    }

    public string CurrentLanguage => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("en", StringComparison.OrdinalIgnoreCase)
        ? "EN"
        : "BG";

    public bool IsEnglish => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("en", StringComparison.OrdinalIgnoreCase);

    public string Pick(string bg, string en) => IsEnglish ? en : bg;

    public string EmotionLabel(EmotionType emotion) => emotion switch
    {
        EmotionType.Calm => Pick("Спокойствие", "Calm"),
        EmotionType.Joy => Pick("Радост", "Joy"),
        EmotionType.Nostalgia => Pick("Носталгия", "Nostalgia"),
        EmotionType.Tension => Pick("Напрежение", "Tension"),
        EmotionType.Inspiration => Pick("Вдъхновение", "Inspiration"),
        EmotionType.Energetic => Pick("Енергично", "Energetic"),
        EmotionType.Romantic => Pick("Романтика", "Romantic"),
        EmotionType.Social => Pick("Социално", "Social"),
        EmotionType.Happy => Pick("Щастие", "Happy"),
        EmotionType.Sad => Pick("Тъга", "Sad"),
        EmotionType.Anxiety => Pick("Тревожност", "Anxiety"),
        EmotionType.Relaxed => Pick("Релакс", "Relaxed"),
        EmotionType.Angry => Pick("Гняв", "Angry"),
        EmotionType.Bored => Pick("Скука", "Bored"),
        EmotionType.Safe => Pick("Сигурност", "Safe"),
        EmotionType.Unsafe => Pick("Опасност", "Unsafe"),
        EmotionType.Excited => Pick("Еуфория", "Excited"),
        EmotionType.Lonely => Pick("Самота", "Lonely"),
        _ => emotion.ToString()
    };

    public string PlaceTypeLabel(PlaceType type) => type switch
    {
        PlaceType.Park => Pick("Парк", "Park"),
        PlaceType.Garden => Pick("Градина", "Garden"),
        PlaceType.Forest => Pick("Гора", "Forest"),
        PlaceType.RiverSide => Pick("Край река", "Riverside"),
        PlaceType.Lake => Pick("Езеро", "Lake"),
        PlaceType.Cafe => Pick("Кафе", "Cafe"),
        PlaceType.Restaurant => Pick("Ресторант", "Restaurant"),
        PlaceType.Bar => Pick("Бар", "Bar"),
        PlaceType.Club => Pick("Клуб", "Club"),
        PlaceType.CulturalSite => Pick("Културен обект", "Cultural site"),
        PlaceType.Museum => Pick("Музей", "Museum"),
        PlaceType.Gallery => Pick("Галерия", "Gallery"),
        PlaceType.Theater => Pick("Театър", "Theater"),
        PlaceType.Cinema => Pick("Кино", "Cinema"),
        PlaceType.Library => Pick("Библиотека", "Library"),
        PlaceType.Viewpoint => Pick("Панорамна гледка", "Viewpoint"),
        PlaceType.Landmark => Pick("Забележителност", "Landmark"),
        PlaceType.HistoricSite => Pick("Историческо място", "Historic site"),
        PlaceType.Sport => Pick("Спорт", "Sport"),
        PlaceType.Gym => Pick("Фитнес", "Gym"),
        PlaceType.Stadium => Pick("Стадион", "Stadium"),
        PlaceType.Playground => Pick("Детска площадка", "Playground"),
        PlaceType.Shopping => Pick("Пазаруване", "Shopping"),
        PlaceType.Mall => Pick("Мол", "Mall"),
        PlaceType.Market => Pick("Пазар", "Market"),
        PlaceType.Education => Pick("Образование", "Education"),
        PlaceType.University => Pick("Университет", "University"),
        PlaceType.School => Pick("Училище", "School"),
        PlaceType.Transport => Pick("Транспорт", "Transport"),
        PlaceType.MetroStation => Pick("Метростанция", "Metro station"),
        PlaceType.BusStop => Pick("Автобусна спирка", "Bus stop"),
        PlaceType.Parking => Pick("Паркинг", "Parking"),
        PlaceType.Health => Pick("Здраве", "Health"),
        PlaceType.Hospital => Pick("Болница", "Hospital"),
        PlaceType.Pharmacy => Pick("Аптека", "Pharmacy"),
        PlaceType.Religious => Pick("Религиозен обект", "Religious site"),
        PlaceType.Church => Pick("Църква", "Church"),
        PlaceType.Office => Pick("Офис", "Office"),
        PlaceType.Coworking => Pick("Coworking", "Coworking"),
        PlaceType.Beach => Pick("Плаж", "Beach"),
        PlaceType.Street => Pick("Улица", "Street"),
        PlaceType.Nightlife => Pick("Нощен живот", "Nightlife"),
        _ => Pick("Друго", "Other")
    };
}
